theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: villamedici-site.web.deuxfleurs.fr
  summary:
    position: hero
  search:
    active: false
  logo:
    header: /assets/images/logo.png
    footer: /assets/images/logo.png
  organizations:
    single:
      backlinks: false
  persons:
    single:
      backlinks: true